### ISSUE TITLE
希望整合网络资源

### ISSUE THREAD

**Issue by 21paradox** [egoist/vanilla-javascript#1]
我所知道的2个比较好的vanilla 站点
使用原生替代 jquery
http://youmightnotneedjquery.com/  

这个虽然是coffee-script写的，细看的话很多有用的原生技巧
https://coffeescript-cookbook.github.io/chapters/strings/generating-a-unique-id

可是我最近比较没时间，辛苦你了

阿里嘎多

**Comment by egoist** [comment]
sure, considering this.
